listofvideos = [
"E1M1MO",
"E1M2MO",
"E1M3MO",
"E1M4MO",
"E1M5MO",
"E1M6MO",
"E1M7MO",
"E1M8MO",
"E1M9MO"
]

// BE SURE TO TYPE FILENAMES, NOT THE TITLES, AND DONT FORGET TO ADD THUMBNAILS